# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linter and tests
concurrency:
  group: reporter-linter-and-tests-${{github.event.pull_request.number}}
  cancel-in-progress: true

on:
  push:
    branches: [master, 2.x]
  pull_request:
    branches: [master, 2.x]

jobs:
  linter-and-tests-on-latest-node:
    runs-on: ubuntu-latest
    name: Linter & Tests (latest node)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: node -v
      - run: npm ci
      - run: npm run lint
      # - run: npm run test:adapter:playwright:example
      - run: npm run build
      - run: npm run test
      - run: npm run test:storage

  playwright-tests:
    runs-on: ubuntu-latest
    name: Playwright Adapter Tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: node -v
      - run: npm ci
      - run: npm run build

      # Install Playwright dependencies
      - name: Install Playwright dependencies
        run: cd example/playwright && npm install
      - name: Install Playwright browsers
        run: npx playwright install chromium

      # Run Playwright adapter tests
      - run: npm run test:playwright

  codecept-tests:
    runs-on: ubuntu-latest
    name: CodeceptJS Adapter Tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: node -v
      - run: npm ci
      - run: npm run build

      # Install CodeceptJS dependencies
      - name: Install CodeceptJS dependencies
        run: cd example/codecept && npm install

      # Run CodeceptJS adapter tests
      - run: npm run test:codecept

  tests:
    runs-on: ubuntu-latest
    needs: linter-and-tests-on-latest-node
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Tests (node ${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run test:storage
