# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linter and tests
concurrency:
  group: reporter-linter-and-tests-${{github.event.pull_request.number}}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linter-and-tests-on-latest-node:
    runs-on: ubuntu-latest
    name: Linter&tests (latest node)
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: node -v
      - run: npm i
      - run: npm run lint
      - run: npm run pretty:fix
      - run: npm run test
      - run: npm run test:storage

  tests:
    runs-on: ubuntu-latest
    needs: linter-and-tests-on-latest-node
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Tests (node ${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run test
      - run: npm run test:storage
