name: Publish TESTCAFE reporter
on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
        working-directory: ./packages/testcafe
      - run: npm publish
        working-directory: ./packages/testcafe
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
