name: Publish REPORTER
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:    
        ref: ${{ github.event.release.target_commitish }}    
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm i
    - run: git config --global user.name "GitHub CD bot"
    - run: git config --global user.email "github-cd-bot@example.com"
                        # remove @beta tag from version
    - run: npm version $(echo "${{ github.event.release.tag_name }}" | awk -F '@' '{ print $1 }')
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        # use "beta" tag if relevant, otherwise use "latest"
        tag: ${{ contains(github.event.release.tag_name, 'beta') && 'beta' || 'latest' }}

    # push the version changes to GitHub
    - run: git push
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
